# Generated by Django 4.1.7 on 2023-05-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="age",
            field=models.CharField(default=23, max_length=200),
            preserve_default=False,
        ),
    ]
